import 'package:flutter/material.dart';

/// Standard unicode emoji categories shown in the picker (custom space emoji
/// and recently-used are handled separately by the picker UI).
enum EmojiCategory {
  smileys('Smileys', Icons.emoji_emotions_outlined),
  people('People', Icons.emoji_people_outlined),
  nature('Nature', Icons.pets_outlined),
  food('Food', Icons.restaurant_outlined),
  activities('Activities', Icons.sports_esports_outlined),
  travel('Travel', Icons.directions_car_filled_outlined),
  objects('Objects', Icons.lightbulb_outline),
  symbols('Symbols', Icons.emoji_symbols_outlined),
  flags('Flags', Icons.flag_outlined);

  const EmojiCategory(this.label, this.icon);

  final String label;
  final IconData icon;
}

/// A single built-in unicode emoji and its searchable name.
class EmojiEntry {
  const EmojiEntry(this.char, this.name, this.category, [this.keywords = '']);

  /// The unicode character (what gets inserted / reacted with).
  final String char;

  /// Canonical short name (e.g. `joy`), also used as the search key.
  final String name;

  final EmojiCategory category;

  /// Extra space-separated search terms.
  final String keywords;

  bool matches(String query) =>
      name.contains(query) || keywords.contains(query);
}

/// A curated catalog of common unicode emoji. Not exhaustive (the reference
/// client ships ~340 SVGs); this covers the everyday set across all categories
/// and is searchable by name/keyword. Custom space emoji are layered on top by
/// the picker.
const List<EmojiEntry> kEmojiCatalog = [
  // ── Smileys ──────────────────────────────────────────────────────────────
  EmojiEntry('😀', 'grinning', EmojiCategory.smileys, 'smile happy'),
  EmojiEntry('😃', 'smiley', EmojiCategory.smileys, 'happy joy'),
  EmojiEntry('😄', 'smile', EmojiCategory.smileys, 'happy joy laugh'),
  EmojiEntry('😁', 'grin', EmojiCategory.smileys, 'happy'),
  EmojiEntry('😆', 'laughing', EmojiCategory.smileys, 'haha lol'),
  EmojiEntry('😅', 'sweat_smile', EmojiCategory.smileys, 'phew relief'),
  EmojiEntry('🤣', 'rofl', EmojiCategory.smileys, 'rolling laugh lmao'),
  EmojiEntry('😂', 'joy', EmojiCategory.smileys, 'laugh cry tears'),
  EmojiEntry('🙂', 'slight_smile', EmojiCategory.smileys, 'smile'),
  EmojiEntry('🙃', 'upside_down', EmojiCategory.smileys, 'silly'),
  EmojiEntry('😉', 'wink', EmojiCategory.smileys, 'flirt'),
  EmojiEntry('😊', 'blush', EmojiCategory.smileys, 'happy shy'),
  EmojiEntry('😇', 'innocent', EmojiCategory.smileys, 'angel halo'),
  EmojiEntry('🥰', 'smiling_hearts', EmojiCategory.smileys, 'love adore'),
  EmojiEntry('😍', 'heart_eyes', EmojiCategory.smileys, 'love'),
  EmojiEntry('🤩', 'star_struck', EmojiCategory.smileys, 'wow amazed'),
  EmojiEntry('😘', 'kissing_heart', EmojiCategory.smileys, 'kiss love'),
  EmojiEntry('😋', 'yum', EmojiCategory.smileys, 'tasty tongue'),
  EmojiEntry('😜', 'stuck_out_tongue_wink', EmojiCategory.smileys, 'silly'),
  EmojiEntry('🤪', 'zany', EmojiCategory.smileys, 'crazy goofy'),
  EmojiEntry('🤔', 'thinking', EmojiCategory.smileys, 'hmm consider'),
  EmojiEntry('🤐', 'zipper_mouth', EmojiCategory.smileys, 'quiet secret'),
  EmojiEntry('😐', 'neutral', EmojiCategory.smileys, 'meh'),
  EmojiEntry('😑', 'expressionless', EmojiCategory.smileys, 'blank'),
  EmojiEntry('😏', 'smirk', EmojiCategory.smileys, 'smug'),
  EmojiEntry('😒', 'unamused', EmojiCategory.smileys, 'meh annoyed'),
  EmojiEntry('🙄', 'roll_eyes', EmojiCategory.smileys, 'whatever'),
  EmojiEntry('😬', 'grimacing', EmojiCategory.smileys, 'awkward yikes'),
  EmojiEntry('😴', 'sleeping', EmojiCategory.smileys, 'zzz tired'),
  EmojiEntry('😌', 'relieved', EmojiCategory.smileys, 'calm'),
  EmojiEntry('😔', 'pensive', EmojiCategory.smileys, 'sad'),
  EmojiEntry('😪', 'sleepy', EmojiCategory.smileys, 'tired'),
  EmojiEntry('🤤', 'drooling', EmojiCategory.smileys, 'want'),
  EmojiEntry('😷', 'mask', EmojiCategory.smileys, 'sick ill'),
  EmojiEntry('🤒', 'thermometer_face', EmojiCategory.smileys, 'sick fever'),
  EmojiEntry('🤮', 'vomiting', EmojiCategory.smileys, 'sick gross'),
  EmojiEntry('🥳', 'partying', EmojiCategory.smileys, 'celebrate party'),
  EmojiEntry('😎', 'sunglasses', EmojiCategory.smileys, 'cool'),
  EmojiEntry('🤓', 'nerd', EmojiCategory.smileys, 'geek glasses'),
  EmojiEntry('😕', 'confused', EmojiCategory.smileys, 'unsure'),
  EmojiEntry('😟', 'worried', EmojiCategory.smileys, 'concern'),
  EmojiEntry('🙁', 'slight_frown', EmojiCategory.smileys, 'sad'),
  EmojiEntry('😮', 'open_mouth', EmojiCategory.smileys, 'wow surprised'),
  EmojiEntry('😯', 'hushed', EmojiCategory.smileys, 'surprised'),
  EmojiEntry('😲', 'astonished', EmojiCategory.smileys, 'shocked'),
  EmojiEntry('😳', 'flushed', EmojiCategory.smileys, 'embarrassed'),
  EmojiEntry('🥺', 'pleading', EmojiCategory.smileys, 'puppy eyes please'),
  EmojiEntry('😦', 'frowning', EmojiCategory.smileys, 'sad'),
  EmojiEntry('😢', 'cry', EmojiCategory.smileys, 'sad tear'),
  EmojiEntry('😭', 'sob', EmojiCategory.smileys, 'crying bawling'),
  EmojiEntry('😤', 'triumph', EmojiCategory.smileys, 'huff proud'),
  EmojiEntry('😠', 'angry', EmojiCategory.smileys, 'mad'),
  EmojiEntry('😡', 'rage', EmojiCategory.smileys, 'mad furious'),
  EmojiEntry('🤬', 'cursing', EmojiCategory.smileys, 'swear angry'),
  EmojiEntry('😈', 'smiling_imp', EmojiCategory.smileys, 'devil evil'),
  EmojiEntry('💀', 'skull', EmojiCategory.smileys, 'dead death'),
  EmojiEntry('💩', 'poop', EmojiCategory.smileys, 'poo crap'),
  EmojiEntry('🤡', 'clown', EmojiCategory.smileys, 'joke'),
  EmojiEntry('👻', 'ghost', EmojiCategory.smileys, 'boo spooky'),
  EmojiEntry('👽', 'alien', EmojiCategory.smileys, 'ufo space'),
  EmojiEntry('🤖', 'robot', EmojiCategory.smileys, 'bot'),
  // ── People & hands ─────────────────────────────────────────────────────────
  EmojiEntry('👋', 'wave', EmojiCategory.people, 'hello hi bye'),
  EmojiEntry('🤚', 'raised_back_hand', EmojiCategory.people, 'stop'),
  EmojiEntry('✋', 'raised_hand', EmojiCategory.people, 'stop high five'),
  EmojiEntry('👌', 'ok_hand', EmojiCategory.people, 'okay perfect'),
  EmojiEntry('🤌', 'pinched_fingers', EmojiCategory.people, 'italian'),
  EmojiEntry('✌️', 'victory', EmojiCategory.people, 'peace'),
  EmojiEntry('🤞', 'crossed_fingers', EmojiCategory.people, 'luck hope'),
  EmojiEntry('🤟', 'love_you_gesture', EmojiCategory.people, 'ily'),
  EmojiEntry('🤘', 'horns', EmojiCategory.people, 'rock metal'),
  EmojiEntry('👈', 'point_left', EmojiCategory.people, ''),
  EmojiEntry('👉', 'point_right', EmojiCategory.people, ''),
  EmojiEntry('👆', 'point_up', EmojiCategory.people, ''),
  EmojiEntry('👇', 'point_down', EmojiCategory.people, ''),
  EmojiEntry('☝️', 'point_up_one', EmojiCategory.people, 'index'),
  EmojiEntry('👍', 'thumbsup', EmojiCategory.people, 'yes like approve +1'),
  EmojiEntry('👎', 'thumbsdown', EmojiCategory.people, 'no dislike -1'),
  EmojiEntry('✊', 'fist', EmojiCategory.people, 'power'),
  EmojiEntry('👊', 'punch', EmojiCategory.people, 'bump'),
  EmojiEntry('👏', 'clap', EmojiCategory.people, 'applause bravo'),
  EmojiEntry('🙌', 'raised_hands', EmojiCategory.people, 'praise yay'),
  EmojiEntry('🤝', 'handshake', EmojiCategory.people, 'deal agree'),
  EmojiEntry('🙏', 'pray', EmojiCategory.people, 'please thanks hope'),
  EmojiEntry('💪', 'muscle', EmojiCategory.people, 'strong flex'),
  EmojiEntry('🫶', 'heart_hands', EmojiCategory.people, 'love'),
  EmojiEntry('👀', 'eyes', EmojiCategory.people, 'look see'),
  EmojiEntry('🧠', 'brain', EmojiCategory.people, 'smart think'),
  EmojiEntry('👶', 'baby', EmojiCategory.people, 'infant'),
  EmojiEntry('🧑', 'person', EmojiCategory.people, 'adult'),
  EmojiEntry('👨', 'man', EmojiCategory.people, 'male'),
  EmojiEntry('👩', 'woman', EmojiCategory.people, 'female'),
  EmojiEntry('🧓', 'older_person', EmojiCategory.people, 'elderly'),
  // ── Nature ─────────────────────────────────────────────────────────────────
  EmojiEntry('🐶', 'dog', EmojiCategory.nature, 'puppy pet'),
  EmojiEntry('🐱', 'cat', EmojiCategory.nature, 'kitten pet'),
  EmojiEntry('🐭', 'mouse', EmojiCategory.nature, ''),
  EmojiEntry('🐹', 'hamster', EmojiCategory.nature, ''),
  EmojiEntry('🐰', 'rabbit', EmojiCategory.nature, 'bunny'),
  EmojiEntry('🦊', 'fox', EmojiCategory.nature, ''),
  EmojiEntry('🐻', 'bear', EmojiCategory.nature, ''),
  EmojiEntry('🐼', 'panda', EmojiCategory.nature, ''),
  EmojiEntry('🐨', 'koala', EmojiCategory.nature, ''),
  EmojiEntry('🐯', 'tiger', EmojiCategory.nature, ''),
  EmojiEntry('🦁', 'lion', EmojiCategory.nature, ''),
  EmojiEntry('🐮', 'cow', EmojiCategory.nature, ''),
  EmojiEntry('🐷', 'pig', EmojiCategory.nature, ''),
  EmojiEntry('🐸', 'frog', EmojiCategory.nature, ''),
  EmojiEntry('🐵', 'monkey_face', EmojiCategory.nature, ''),
  EmojiEntry('🐔', 'chicken', EmojiCategory.nature, ''),
  EmojiEntry('🐧', 'penguin', EmojiCategory.nature, ''),
  EmojiEntry('🐦', 'bird', EmojiCategory.nature, ''),
  EmojiEntry('🦆', 'duck', EmojiCategory.nature, ''),
  EmojiEntry('🦉', 'owl', EmojiCategory.nature, ''),
  EmojiEntry('🐺', 'wolf', EmojiCategory.nature, ''),
  EmojiEntry('🐝', 'bee', EmojiCategory.nature, 'honey'),
  EmojiEntry('🦋', 'butterfly', EmojiCategory.nature, ''),
  EmojiEntry('🐢', 'turtle', EmojiCategory.nature, ''),
  EmojiEntry('🐍', 'snake', EmojiCategory.nature, ''),
  EmojiEntry('🐙', 'octopus', EmojiCategory.nature, ''),
  EmojiEntry('🐠', 'fish', EmojiCategory.nature, ''),
  EmojiEntry('🐬', 'dolphin', EmojiCategory.nature, ''),
  EmojiEntry('🐳', 'whale', EmojiCategory.nature, ''),
  EmojiEntry('🌵', 'cactus', EmojiCategory.nature, 'plant'),
  EmojiEntry('🌲', 'evergreen_tree', EmojiCategory.nature, ''),
  EmojiEntry('🌴', 'palm_tree', EmojiCategory.nature, ''),
  EmojiEntry('🌸', 'cherry_blossom', EmojiCategory.nature, 'flower sakura'),
  EmojiEntry('🌹', 'rose', EmojiCategory.nature, 'flower'),
  EmojiEntry('🌻', 'sunflower', EmojiCategory.nature, 'flower'),
  EmojiEntry('🍀', 'four_leaf_clover', EmojiCategory.nature, 'luck'),
  EmojiEntry('🔥', 'fire', EmojiCategory.nature, 'lit hot flame'),
  EmojiEntry('⭐', 'star', EmojiCategory.nature, ''),
  EmojiEntry('🌟', 'star2', EmojiCategory.nature, 'glowing sparkle'),
  EmojiEntry('✨', 'sparkles', EmojiCategory.nature, 'shiny magic'),
  EmojiEntry('⚡', 'zap', EmojiCategory.nature, 'lightning'),
  EmojiEntry('🌈', 'rainbow', EmojiCategory.nature, ''),
  EmojiEntry('☀️', 'sunny', EmojiCategory.nature, 'sun'),
  EmojiEntry('⛅', 'partly_sunny', EmojiCategory.nature, 'cloud'),
  EmojiEntry('☁️', 'cloud', EmojiCategory.nature, ''),
  EmojiEntry('🌙', 'crescent_moon', EmojiCategory.nature, 'night'),
  EmojiEntry('❄️', 'snowflake', EmojiCategory.nature, 'cold winter'),
  EmojiEntry('💧', 'droplet', EmojiCategory.nature, 'water'),
  EmojiEntry('🌊', 'ocean', EmojiCategory.nature, 'wave water'),
  // ── Food ───────────────────────────────────────────────────────────────────
  EmojiEntry('🍎', 'apple', EmojiCategory.food, 'fruit'),
  EmojiEntry('🍊', 'tangerine', EmojiCategory.food, 'orange fruit'),
  EmojiEntry('🍌', 'banana', EmojiCategory.food, 'fruit'),
  EmojiEntry('🍉', 'watermelon', EmojiCategory.food, 'fruit'),
  EmojiEntry('🍇', 'grapes', EmojiCategory.food, 'fruit'),
  EmojiEntry('🍓', 'strawberry', EmojiCategory.food, 'fruit'),
  EmojiEntry('🍒', 'cherries', EmojiCategory.food, 'fruit'),
  EmojiEntry('🍑', 'peach', EmojiCategory.food, 'fruit butt'),
  EmojiEntry('🥑', 'avocado', EmojiCategory.food, ''),
  EmojiEntry('🍅', 'tomato', EmojiCategory.food, ''),
  EmojiEntry('🌽', 'corn', EmojiCategory.food, ''),
  EmojiEntry('🥕', 'carrot', EmojiCategory.food, ''),
  EmojiEntry('🍔', 'hamburger', EmojiCategory.food, 'burger'),
  EmojiEntry('🍟', 'fries', EmojiCategory.food, 'chips'),
  EmojiEntry('🍕', 'pizza', EmojiCategory.food, ''),
  EmojiEntry('🌭', 'hotdog', EmojiCategory.food, ''),
  EmojiEntry('🌮', 'taco', EmojiCategory.food, ''),
  EmojiEntry('🍣', 'sushi', EmojiCategory.food, ''),
  EmojiEntry('🍜', 'ramen', EmojiCategory.food, 'noodles'),
  EmojiEntry('🍩', 'doughnut', EmojiCategory.food, 'donut'),
  EmojiEntry('🍪', 'cookie', EmojiCategory.food, ''),
  EmojiEntry('🎂', 'birthday', EmojiCategory.food, 'cake'),
  EmojiEntry('🍰', 'cake', EmojiCategory.food, 'dessert'),
  EmojiEntry('🍫', 'chocolate', EmojiCategory.food, ''),
  EmojiEntry('🍿', 'popcorn', EmojiCategory.food, ''),
  EmojiEntry('☕', 'coffee', EmojiCategory.food, 'tea hot'),
  EmojiEntry('🍵', 'tea', EmojiCategory.food, ''),
  EmojiEntry('🍺', 'beer', EmojiCategory.food, 'drink'),
  EmojiEntry('🍻', 'beers', EmojiCategory.food, 'cheers'),
  EmojiEntry('🍷', 'wine', EmojiCategory.food, 'drink'),
  EmojiEntry('🥂', 'champagne', EmojiCategory.food, 'cheers toast'),
  EmojiEntry('🍸', 'cocktail', EmojiCategory.food, 'drink'),
  // ── Activities ───────────────────────────────────────────────────────────
  EmojiEntry('⚽', 'soccer', EmojiCategory.activities, 'football'),
  EmojiEntry('🏀', 'basketball', EmojiCategory.activities, ''),
  EmojiEntry('🏈', 'football', EmojiCategory.activities, 'american'),
  EmojiEntry('⚾', 'baseball', EmojiCategory.activities, ''),
  EmojiEntry('🎾', 'tennis', EmojiCategory.activities, ''),
  EmojiEntry('🏐', 'volleyball', EmojiCategory.activities, ''),
  EmojiEntry('🎱', 'pool_8_ball', EmojiCategory.activities, 'billiards'),
  EmojiEntry('🏓', 'ping_pong', EmojiCategory.activities, 'table tennis'),
  EmojiEntry('🥅', 'goal', EmojiCategory.activities, 'net'),
  EmojiEntry('🏆', 'trophy', EmojiCategory.activities, 'win champion'),
  EmojiEntry('🥇', 'first_place', EmojiCategory.activities, 'gold medal'),
  EmojiEntry('🥈', 'second_place', EmojiCategory.activities, 'silver medal'),
  EmojiEntry('🥉', 'third_place', EmojiCategory.activities, 'bronze medal'),
  EmojiEntry('🎮', 'video_game', EmojiCategory.activities, 'gaming controller'),
  EmojiEntry('🕹️', 'joystick', EmojiCategory.activities, 'arcade'),
  EmojiEntry('🎲', 'game_die', EmojiCategory.activities, 'dice'),
  EmojiEntry('🎯', 'dart', EmojiCategory.activities, 'target bullseye'),
  EmojiEntry('🎨', 'art', EmojiCategory.activities, 'paint palette'),
  EmojiEntry('🎤', 'microphone', EmojiCategory.activities, 'sing karaoke'),
  EmojiEntry('🎧', 'headphones', EmojiCategory.activities, 'music'),
  EmojiEntry('🎸', 'guitar', EmojiCategory.activities, 'music'),
  EmojiEntry('🎹', 'piano', EmojiCategory.activities, 'music keyboard'),
  EmojiEntry('🥁', 'drum', EmojiCategory.activities, 'music'),
  EmojiEntry('🎉', 'tada', EmojiCategory.activities, 'party celebrate hooray'),
  EmojiEntry('🎊', 'confetti', EmojiCategory.activities, 'party'),
  EmojiEntry('🎁', 'gift', EmojiCategory.activities, 'present'),
  // ── Travel & places ────────────────────────────────────────────────────────
  EmojiEntry('🚗', 'car', EmojiCategory.travel, 'auto'),
  EmojiEntry('🚕', 'taxi', EmojiCategory.travel, 'cab'),
  EmojiEntry('🚌', 'bus', EmojiCategory.travel, ''),
  EmojiEntry('🏎️', 'race_car', EmojiCategory.travel, 'fast'),
  EmojiEntry('🚓', 'police_car', EmojiCategory.travel, ''),
  EmojiEntry('🚑', 'ambulance', EmojiCategory.travel, ''),
  EmojiEntry('🚒', 'fire_engine', EmojiCategory.travel, ''),
  EmojiEntry('🚲', 'bike', EmojiCategory.travel, 'bicycle'),
  EmojiEntry('🛵', 'scooter', EmojiCategory.travel, ''),
  EmojiEntry('✈️', 'airplane', EmojiCategory.travel, 'flight plane'),
  EmojiEntry('🚀', 'rocket', EmojiCategory.travel, 'launch space ship'),
  EmojiEntry('🚁', 'helicopter', EmojiCategory.travel, ''),
  EmojiEntry('⛵', 'sailboat', EmojiCategory.travel, 'boat'),
  EmojiEntry('🚢', 'ship', EmojiCategory.travel, 'cruise'),
  EmojiEntry('🚂', 'train', EmojiCategory.travel, ''),
  EmojiEntry('🏠', 'house', EmojiCategory.travel, 'home'),
  EmojiEntry('🏢', 'office', EmojiCategory.travel, 'building'),
  EmojiEntry('🏥', 'hospital', EmojiCategory.travel, ''),
  EmojiEntry('🗽', 'statue_of_liberty', EmojiCategory.travel, 'nyc'),
  EmojiEntry('🗼', 'tokyo_tower', EmojiCategory.travel, ''),
  EmojiEntry('🏰', 'castle', EmojiCategory.travel, ''),
  EmojiEntry('⛰️', 'mountain', EmojiCategory.travel, ''),
  EmojiEntry('🏖️', 'beach', EmojiCategory.travel, 'sand vacation'),
  EmojiEntry('🌋', 'volcano', EmojiCategory.travel, ''),
  EmojiEntry('🗺️', 'world_map', EmojiCategory.travel, 'travel'),
  // ── Objects ────────────────────────────────────────────────────────────────
  EmojiEntry('⌚', 'watch', EmojiCategory.objects, 'time'),
  EmojiEntry('📱', 'phone', EmojiCategory.objects, 'mobile cell'),
  EmojiEntry('💻', 'laptop', EmojiCategory.objects, 'computer'),
  EmojiEntry('🖥️', 'desktop', EmojiCategory.objects, 'computer monitor'),
  EmojiEntry('⌨️', 'keyboard', EmojiCategory.objects, ''),
  EmojiEntry('🖱️', 'mouse_three_button', EmojiCategory.objects, 'computer'),
  EmojiEntry('🖨️', 'printer', EmojiCategory.objects, ''),
  EmojiEntry('💾', 'floppy_disk', EmojiCategory.objects, 'save'),
  EmojiEntry('💡', 'bulb', EmojiCategory.objects, 'idea light'),
  EmojiEntry('🔦', 'flashlight', EmojiCategory.objects, 'torch'),
  EmojiEntry('🔋', 'battery', EmojiCategory.objects, 'power'),
  EmojiEntry('🔌', 'plug', EmojiCategory.objects, 'electric'),
  EmojiEntry('📷', 'camera', EmojiCategory.objects, 'photo'),
  EmojiEntry('🎥', 'movie_camera', EmojiCategory.objects, 'film'),
  EmojiEntry('📺', 'tv', EmojiCategory.objects, 'television'),
  EmojiEntry('📻', 'radio', EmojiCategory.objects, ''),
  EmojiEntry('⏰', 'alarm_clock', EmojiCategory.objects, 'time'),
  EmojiEntry('📚', 'books', EmojiCategory.objects, 'read library'),
  EmojiEntry('✏️', 'pencil', EmojiCategory.objects, 'write'),
  EmojiEntry('📝', 'memo', EmojiCategory.objects, 'note write'),
  EmojiEntry('📌', 'pushpin', EmojiCategory.objects, 'pin'),
  EmojiEntry('📎', 'paperclip', EmojiCategory.objects, 'attach'),
  EmojiEntry('🔍', 'mag', EmojiCategory.objects, 'search magnify'),
  EmojiEntry('🔒', 'lock', EmojiCategory.objects, 'secure'),
  EmojiEntry('🔑', 'key', EmojiCategory.objects, 'unlock'),
  EmojiEntry('🔨', 'hammer', EmojiCategory.objects, 'tool build'),
  EmojiEntry('🛠️', 'tools', EmojiCategory.objects, 'fix repair'),
  EmojiEntry('💰', 'moneybag', EmojiCategory.objects, 'cash rich'),
  EmojiEntry('💵', 'dollar', EmojiCategory.objects, 'money cash'),
  EmojiEntry('💎', 'gem', EmojiCategory.objects, 'diamond jewel'),
  EmojiEntry('🎈', 'balloon', EmojiCategory.objects, 'party'),
  EmojiEntry('📦', 'package', EmojiCategory.objects, 'box ship'),
  // ── Symbols ────────────────────────────────────────────────────────────────
  EmojiEntry('❤️', 'heart', EmojiCategory.symbols, 'love red'),
  EmojiEntry('🧡', 'orange_heart', EmojiCategory.symbols, 'love'),
  EmojiEntry('💛', 'yellow_heart', EmojiCategory.symbols, 'love'),
  EmojiEntry('💚', 'green_heart', EmojiCategory.symbols, 'love'),
  EmojiEntry('💙', 'blue_heart', EmojiCategory.symbols, 'love'),
  EmojiEntry('💜', 'purple_heart', EmojiCategory.symbols, 'love'),
  EmojiEntry('🖤', 'black_heart', EmojiCategory.symbols, 'love'),
  EmojiEntry('🤍', 'white_heart', EmojiCategory.symbols, 'love'),
  EmojiEntry('💔', 'broken_heart', EmojiCategory.symbols, 'sad'),
  EmojiEntry('❣️', 'heart_exclamation', EmojiCategory.symbols, 'love'),
  EmojiEntry('💕', 'two_hearts', EmojiCategory.symbols, 'love'),
  EmojiEntry('💯', '100', EmojiCategory.symbols, 'hundred perfect score'),
  EmojiEntry('✅', 'white_check_mark', EmojiCategory.symbols, 'done yes ok'),
  EmojiEntry('☑️', 'ballot_check', EmojiCategory.symbols, 'checkbox'),
  EmojiEntry('✔️', 'heavy_check_mark', EmojiCategory.symbols, 'done'),
  EmojiEntry('❌', 'x', EmojiCategory.symbols, 'no cross wrong'),
  EmojiEntry('❎', 'negative_squared_cross', EmojiCategory.symbols, 'no'),
  EmojiEntry('➕', 'heavy_plus', EmojiCategory.symbols, 'add'),
  EmojiEntry('➖', 'heavy_minus', EmojiCategory.symbols, 'subtract'),
  EmojiEntry('❓', 'question', EmojiCategory.symbols, 'help'),
  EmojiEntry('❗', 'exclamation', EmojiCategory.symbols, 'warning'),
  EmojiEntry('⚠️', 'warning', EmojiCategory.symbols, 'caution'),
  EmojiEntry('🚫', 'no_entry_sign', EmojiCategory.symbols, 'forbidden ban'),
  EmojiEntry('💤', 'zzz', EmojiCategory.symbols, 'sleep'),
  EmojiEntry('💢', 'anger', EmojiCategory.symbols, 'mad'),
  EmojiEntry('💥', 'boom', EmojiCategory.symbols, 'explosion collision'),
  EmojiEntry('♻️', 'recycle', EmojiCategory.symbols, 'green'),
  EmojiEntry('🔔', 'bell', EmojiCategory.symbols, 'notification'),
  EmojiEntry('🔕', 'no_bell', EmojiCategory.symbols, 'mute'),
  EmojiEntry('🔊', 'loud_sound', EmojiCategory.symbols, 'volume'),
  EmojiEntry('🔇', 'mute', EmojiCategory.symbols, 'silent'),
  EmojiEntry('🏳️', 'white_flag', EmojiCategory.symbols, 'surrender'),
  EmojiEntry('🏴', 'black_flag', EmojiCategory.symbols, ''),
  // ── Flags ──────────────────────────────────────────────────────────────────
  EmojiEntry('🏁', 'checkered_flag', EmojiCategory.flags, 'race finish'),
  EmojiEntry('🚩', 'triangular_flag', EmojiCategory.flags, 'red'),
  EmojiEntry('🏳️‍🌈', 'rainbow_flag', EmojiCategory.flags, 'pride lgbt'),
  EmojiEntry('🇺🇸', 'flag_us', EmojiCategory.flags, 'usa america'),
  EmojiEntry('🇬🇧', 'flag_gb', EmojiCategory.flags, 'uk britain'),
  EmojiEntry('🇨🇦', 'flag_ca', EmojiCategory.flags, 'canada'),
  EmojiEntry('🇦🇺', 'flag_au', EmojiCategory.flags, 'australia'),
  EmojiEntry('🇩🇪', 'flag_de', EmojiCategory.flags, 'germany'),
  EmojiEntry('🇫🇷', 'flag_fr', EmojiCategory.flags, 'france'),
  EmojiEntry('🇪🇸', 'flag_es', EmojiCategory.flags, 'spain'),
  EmojiEntry('🇮🇹', 'flag_it', EmojiCategory.flags, 'italy'),
  EmojiEntry('🇯🇵', 'flag_jp', EmojiCategory.flags, 'japan'),
  EmojiEntry('🇰🇷', 'flag_kr', EmojiCategory.flags, 'korea'),
  EmojiEntry('🇨🇳', 'flag_cn', EmojiCategory.flags, 'china'),
  EmojiEntry('🇧🇷', 'flag_br', EmojiCategory.flags, 'brazil'),
  EmojiEntry('🇮🇳', 'flag_in', EmojiCategory.flags, 'india'),
];
