#!/usr/bin/env python3
"""Reproducible v1 Wasm packages. No external compiler or archive format."""
import argparse
import base64
import hashlib
import json
from pathlib import Path


def leb(value, signed=False):
    out = bytearray()
    while True:
        b = value & 127
        value >>= 7
        done = (value == 0 and (not signed or b & 64 == 0)) or (signed and value == -1 and b & 64 != 0)
        out.append(b if done else b | 128)
        if done:
            return bytes(out)


def vector(items):
    return leb(len(items)) + b''.join(items)


def name(value):
    value = value.encode()
    return leb(len(value)) + value


def section(index, data):
    return bytes([index]) + leb(len(data)) + data


def const(value):
    return b'\x41' + leb(value, True)


def call(index):
    return b'\x10' + leb(index)


def module(game='chess', render=None, input_code=None):
    types = [(2, 1), (7, 0), (3, 0), (0, 0)]
    result = b'\0asm\x01\0\0\0'
    result += section(1, vector([b'\x60' + vector([b'\x7f'] * p) + vector([b'\x7f'] * r) for p, r in types]))
    result += section(2, vector([name('daccord_v1') + name(n) + b'\0' + leb(i) for i, n in enumerate(['read_state', 'draw', 'action'])]))
    result += section(3, vector([leb(3), leb(2)]))
    result += section(7, vector([name('render') + b'\0' + leb(3), name('input') + b'\0' + leb(4)]))
    if render is None:
        render = b''
        if game == 'chess':
            for cell in range(64):
                render += b''.join(const(v) for v in [0, cell, (cell % 8) * 128, (7 - cell // 8) * 128, 128, 128])
                render += const(0) + const(cell) + call(0) + call(1)
        else:
            for item in range(3):
                render += const(1) + const(item)
                for coord in range(4):
                    render += const(1) + const(item * 4 + coord) + call(0)
                render += const(item) + call(1)
    if input_code is None:
        input_code = b'\x20\0\x20\x01\x20\x02' + call(2)
    bodies = [b'\0' + render + b'\x0b', b'\0' + input_code + b'\x0b']
    return result + section(10, vector([leb(len(b)) + b for b in bodies]))


def package(game):
    wasm = module(game)
    manifest = dict(id=game, name=game.title(), description='Two-player ' + game,
                    publisher='Daccord Project', version='1.0.0', host_api=1,
                    runtime='wasm-bounded-v1', authority=game,
                    session_mode='turn_based' if game == 'chess' else 'real_time',
                    min_players=2, max_players=2, max_spectators=16,
                    platforms=['linux', 'windows', 'macos', 'android', 'ios', 'web'],
                    capabilities=['session.read', 'session.action', 'draw'],
                    module_sha256=hashlib.sha256(wasm).hexdigest())
    return dict(manifest=manifest, module=base64.b64encode(wasm).decode())


if __name__ == '__main__':
    parser = argparse.ArgumentParser()
    parser.add_argument('--output', default='tools/experiences/packages')
    parser.add_argument('--test-fixture', help='Also emit a portable Dart fixture with the exact signed payload')
    args = parser.parse_args()
    output = Path(args.output)
    output.mkdir(parents=True, exist_ok=True)
    for game in ['chess', 'pong']:
        (output / (game + '.json')).write_text(json.dumps(package(game), sort_keys=True, separators=(',', ':')) + '\n')
        (output / (game + '.wasm')).write_bytes(module(game))
    if args.test_fixture:
        payload = (output / 'chess.json').read_text()
        Path(args.test_fixture).write_text(
            "// Generated by tools/experiences/build_reference.py; do not edit.\n"
            "const referenceChessPackage = r\"\"\"" + payload + "\"\"\";\n")
