class_name EmojiData

## Static emoji catalog for the emoji picker.
## Maps categories to arrays of {name, codepoint} entries.
## Codepoints reference Twemoji SVGs in theme/emoji/.

enum Category { SMILEYS, PEOPLE, NATURE, FOOD, ACTIVITIES, TRAVEL, OBJECTS, SYMBOLS, FLAGS }

const CATEGORY_NAMES := {
	Category.SMILEYS: "Smileys & Emotion",
	Category.PEOPLE: "People & Body",
	Category.NATURE: "Animals & Nature",
	Category.FOOD: "Food & Drink",
	Category.ACTIVITIES: "Activities",
	Category.TRAVEL: "Travel & Places",
	Category.OBJECTS: "Objects",
	Category.SYMBOLS: "Symbols",
	Category.FLAGS: "Flags",
}

const CATEGORY_ICONS := {
	Category.SMILEYS: "1f600",
	Category.PEOPLE: "1f44b",
	Category.NATURE: "1f436",
	Category.FOOD: "1f34e",
	Category.ACTIVITIES: "26bd",
	Category.TRAVEL: "1f697",
	Category.OBJECTS: "1f4a1",
	Category.SYMBOLS: "2764",
	Category.FLAGS: "1f1fa-1f1f8",
}

const CATALOG := {
	Category.SMILEYS: [
		{"name": "grinning_face", "codepoint": "1f600"},
		{"name": "grinning_big_eyes", "codepoint": "1f603"},
		{"name": "grinning_smiling_eyes", "codepoint": "1f604"},
		{"name": "beaming_face", "codepoint": "1f601"},
		{"name": "grinning_squinting", "codepoint": "1f606"},
		{"name": "grinning_sweat", "codepoint": "1f605"},
		{"name": "rofl", "codepoint": "1f923"},
		{"name": "joy", "codepoint": "1f602"},
		{"name": "slightly_smiling", "codepoint": "1f642"},
		{"name": "winking", "codepoint": "1f609"},
		{"name": "smiling_eyes", "codepoint": "1f60a"},
		{"name": "halo", "codepoint": "1f607"},
		{"name": "hearts_face", "codepoint": "1f970"},
		{"name": "heart_eyes", "codepoint": "1f60d"},
		{"name": "star_struck", "codepoint": "1f929"},
		{"name": "blowing_kiss", "codepoint": "1f618"},
		{"name": "thinking", "codepoint": "1f914"},
		{"name": "rolling_eyes", "codepoint": "1f644"},
		{"name": "crying", "codepoint": "1f62d"},
		{"name": "pleading", "codepoint": "1f97a"},
	],
	Category.PEOPLE: [
		{"name": "wave", "codepoint": "1f44b"},
		{"name": "raised_back_of_hand", "codepoint": "1f91a"},
		{"name": "thumbs_up", "codepoint": "1f44d"},
		{"name": "thumbs_down", "codepoint": "1f44e"},
		{"name": "clap", "codepoint": "1f44f"},
		{"name": "pray", "codepoint": "1f64f"},
		{"name": "muscle", "codepoint": "1f4aa"},
		{"name": "handshake", "codepoint": "1f91d"},
		{"name": "victory", "codepoint": "270c"},
		{"name": "ok_hand", "codepoint": "1f44c"},
		{"name": "fist_bump", "codepoint": "1f44a"},
		{"name": "left_fist", "codepoint": "1f91b"},
		{"name": "right_fist", "codepoint": "1f91c"},
		{"name": "crossed_fingers", "codepoint": "1f91e"},
		{"name": "rock_on", "codepoint": "1f918"},
		{"name": "call_me", "codepoint": "1f919"},
		{"name": "point_left", "codepoint": "1f448"},
		{"name": "point_right", "codepoint": "1f449"},
		{"name": "point_up", "codepoint": "1f446"},
		{"name": "point_down", "codepoint": "1f447"},
	],
	Category.NATURE: [
		{"name": "dog_face", "codepoint": "1f436"},
		{"name": "cat_face", "codepoint": "1f431"},
		{"name": "mouse_face", "codepoint": "1f42d"},
		{"name": "hamster", "codepoint": "1f439"},
		{"name": "rabbit", "codepoint": "1f430"},
		{"name": "fox", "codepoint": "1f98a"},
		{"name": "bear", "codepoint": "1f43b"},
		{"name": "panda", "codepoint": "1f43c"},
		{"name": "koala", "codepoint": "1f428"},
		{"name": "tiger", "codepoint": "1f42f"},
		{"name": "lion", "codepoint": "1f981"},
		{"name": "cow", "codepoint": "1f42e"},
		{"name": "pig", "codepoint": "1f437"},
		{"name": "frog", "codepoint": "1f438"},
		{"name": "monkey_face", "codepoint": "1f435"},
		{"name": "sunflower", "codepoint": "1f33b"},
		{"name": "rose", "codepoint": "1f339"},
		{"name": "hibiscus", "codepoint": "1f33a"},
		{"name": "four_leaf_clover", "codepoint": "1f340"},
		{"name": "evergreen_tree", "codepoint": "1f332"},
	],
	Category.FOOD: [
		{"name": "red_apple", "codepoint": "1f34e"},
		{"name": "orange", "codepoint": "1f34a"},
		{"name": "lemon", "codepoint": "1f34b"},
		{"name": "banana", "codepoint": "1f34c"},
		{"name": "watermelon", "codepoint": "1f349"},
		{"name": "grapes", "codepoint": "1f347"},
		{"name": "strawberry", "codepoint": "1f353"},
		{"name": "peach", "codepoint": "1f351"},
		{"name": "cherries", "codepoint": "1f352"},
		{"name": "pineapple", "codepoint": "1f34d"},
		{"name": "tomato", "codepoint": "1f345"},
		{"name": "avocado", "codepoint": "1f951"},
		{"name": "hamburger", "codepoint": "1f354"},
		{"name": "pizza", "codepoint": "1f355"},
		{"name": "taco", "codepoint": "1f32e"},
		{"name": "burrito", "codepoint": "1f32f"},
		{"name": "popcorn", "codepoint": "1f37f"},
		{"name": "shortcake", "codepoint": "1f370"},
		{"name": "doughnut", "codepoint": "1f369"},
		{"name": "hot_beverage", "codepoint": "2615"},
	],
	Category.ACTIVITIES: [
		{"name": "soccer", "codepoint": "26bd"},
		{"name": "basketball", "codepoint": "1f3c0"},
		{"name": "football", "codepoint": "1f3c8"},
		{"name": "baseball", "codepoint": "26be"},
		{"name": "tennis", "codepoint": "1f3be"},
		{"name": "volleyball", "codepoint": "1f3d0"},
		{"name": "pool_8_ball", "codepoint": "1f3b1"},
		{"name": "bowling", "codepoint": "1f3b3"},
		{"name": "direct_hit", "codepoint": "1f3af"},
		{"name": "trophy", "codepoint": "1f3c6"},
		{"name": "sports_medal", "codepoint": "1f3c5"},
		{"name": "game_die", "codepoint": "1f3b2"},
		{"name": "video_game", "codepoint": "1f3ae"},
		{"name": "artist_palette", "codepoint": "1f3a8"},
		{"name": "performing_arts", "codepoint": "1f3ad"},
		{"name": "musical_note", "codepoint": "1f3b5"},
		{"name": "musical_notes", "codepoint": "1f3b6"},
		{"name": "microphone", "codepoint": "1f3a4"},
		{"name": "headphone", "codepoint": "1f3a7"},
		{"name": "clapper_board", "codepoint": "1f3ac"},
	],
	Category.TRAVEL: [
		{"name": "car", "codepoint": "1f697"},
		{"name": "taxi", "codepoint": "1f695"},
		{"name": "bus", "codepoint": "1f68c"},
		{"name": "police_car", "codepoint": "1f693"},
		{"name": "ambulance", "codepoint": "1f691"},
		{"name": "fire_engine", "codepoint": "1f692"},
		{"name": "airplane", "codepoint": "2708"},
		{"name": "rocket", "codepoint": "1f680"},
		{"name": "flying_saucer", "codepoint": "1f6f8"},
		{"name": "ship", "codepoint": "1f6a2"},
		{"name": "house", "codepoint": "1f3e0"},
		{"name": "building_construction", "codepoint": "1f3d7"},
		{"name": "mountain", "codepoint": "26f0"},
		{"name": "beach", "codepoint": "1f3d6"},
		{"name": "earth_americas", "codepoint": "1f30e"},
		{"name": "earth_asia", "codepoint": "1f30f"},
		{"name": "star", "codepoint": "2b50"},
		{"name": "crescent_moon", "codepoint": "1f319"},
		{"name": "sun", "codepoint": "2600"},
		{"name": "rainbow", "codepoint": "1f308"},
	],
	Category.OBJECTS: [
		{"name": "watch", "codepoint": "231a"},
		{"name": "mobile_phone", "codepoint": "1f4f1"},
		{"name": "laptop", "codepoint": "1f4bb"},
		{"name": "keyboard", "codepoint": "2328"},
		{"name": "light_bulb", "codepoint": "1f4a1"},
		{"name": "books", "codepoint": "1f4da"},
		{"name": "open_book", "codepoint": "1f4d6"},
		{"name": "pencil", "codepoint": "270f"},
		{"name": "memo", "codepoint": "1f4dd"},
		{"name": "paperclip", "codepoint": "1f4ce"},
		{"name": "pushpin", "codepoint": "1f4cc"},
		{"name": "scissors", "codepoint": "2702"},
		{"name": "wrench", "codepoint": "1f527"},
		{"name": "hammer", "codepoint": "1f528"},
		{"name": "magnifying_glass", "codepoint": "1f50d"},
		{"name": "locked", "codepoint": "1f512"},
		{"name": "key", "codepoint": "1f511"},
		{"name": "gift", "codepoint": "1f381"},
		{"name": "party_popper", "codepoint": "1f389"},
		{"name": "bell", "codepoint": "1f514"},
	],
	Category.SYMBOLS: [
		{"name": "heart", "codepoint": "2764"},
		{"name": "orange_heart", "codepoint": "1f9e1"},
		{"name": "yellow_heart", "codepoint": "1f49b"},
		{"name": "green_heart", "codepoint": "1f49a"},
		{"name": "blue_heart", "codepoint": "1f499"},
		{"name": "purple_heart", "codepoint": "1f49c"},
		{"name": "black_heart", "codepoint": "1f5a4"},
		{"name": "broken_heart", "codepoint": "1f494"},
		{"name": "two_hearts", "codepoint": "1f495"},
		{"name": "100", "codepoint": "1f4af"},
		{"name": "check_mark", "codepoint": "2705"},
		{"name": "cross_mark", "codepoint": "274c"},
		{"name": "exclamation", "codepoint": "2757"},
		{"name": "question", "codepoint": "2753"},
		{"name": "eyes", "codepoint": "1f440"},
		{"name": "collision", "codepoint": "1f4a5"},
		{"name": "anger", "codepoint": "1f4a2"},
		{"name": "dizzy", "codepoint": "1f4ab"},
		{"name": "zzz", "codepoint": "1f4a4"},
		{"name": "fire", "codepoint": "1f525"},
	],
	Category.FLAGS: [
		{"name": "flag_us", "codepoint": "1f1fa-1f1f8"},
		{"name": "flag_gb", "codepoint": "1f1ec-1f1e7"},
		{"name": "flag_ca", "codepoint": "1f1e8-1f1e6"},
		{"name": "flag_au", "codepoint": "1f1e6-1f1fa"},
		{"name": "flag_de", "codepoint": "1f1e9-1f1ea"},
		{"name": "flag_fr", "codepoint": "1f1eb-1f1f7"},
		{"name": "flag_es", "codepoint": "1f1ea-1f1f8"},
		{"name": "flag_it", "codepoint": "1f1ee-1f1f9"},
		{"name": "flag_jp", "codepoint": "1f1ef-1f1f5"},
		{"name": "flag_kr", "codepoint": "1f1f0-1f1f7"},
		{"name": "flag_cn", "codepoint": "1f1e8-1f1f3"},
		{"name": "flag_in", "codepoint": "1f1ee-1f1f3"},
		{"name": "flag_br", "codepoint": "1f1e7-1f1f7"},
		{"name": "flag_mx", "codepoint": "1f1f2-1f1fd"},
		{"name": "flag_ru", "codepoint": "1f1f7-1f1fa"},
		{"name": "flag_nl", "codepoint": "1f1f3-1f1f1"},
		{"name": "flag_se", "codepoint": "1f1f8-1f1ea"},
		{"name": "flag_no", "codepoint": "1f1f3-1f1f4"},
		{"name": "flag_fi", "codepoint": "1f1eb-1f1ee"},
		{"name": "flag_dk", "codepoint": "1f1e9-1f1f0"},
		{"name": "flag_ie", "codepoint": "1f1ee-1f1ea"},
		{"name": "flag_pt", "codepoint": "1f1f5-1f1f9"},
		{"name": "flag_ch", "codepoint": "1f1e8-1f1ed"},
		{"name": "flag_be", "codepoint": "1f1e7-1f1ea"},
		{"name": "flag_at", "codepoint": "1f1e6-1f1f9"},
		{"name": "flag_pl", "codepoint": "1f1f5-1f1f1"},
		{"name": "flag_tr", "codepoint": "1f1f9-1f1f7"},
		{"name": "flag_ua", "codepoint": "1f1fa-1f1e6"},
		{"name": "flag_nz", "codepoint": "1f1f3-1f1ff"},
		{"name": "flag_ar", "codepoint": "1f1e6-1f1f7"},
	],
}

const TEXTURES := {
	# Smileys & Emotion
	"grinning_face": preload("res://assets/theme/emoji/1f600.svg"),
	"grinning_big_eyes": preload("res://assets/theme/emoji/1f603.svg"),
	"grinning_smiling_eyes": preload("res://assets/theme/emoji/1f604.svg"),
	"beaming_face": preload("res://assets/theme/emoji/1f601.svg"),
	"grinning_squinting": preload("res://assets/theme/emoji/1f606.svg"),
	"grinning_sweat": preload("res://assets/theme/emoji/1f605.svg"),
	"rofl": preload("res://assets/theme/emoji/1f923.svg"),
	"joy": preload("res://assets/theme/emoji/1f602.svg"),
	"slightly_smiling": preload("res://assets/theme/emoji/1f642.svg"),
	"winking": preload("res://assets/theme/emoji/1f609.svg"),
	"smiling_eyes": preload("res://assets/theme/emoji/1f60a.svg"),
	"halo": preload("res://assets/theme/emoji/1f607.svg"),
	"hearts_face": preload("res://assets/theme/emoji/1f970.svg"),
	"heart_eyes": preload("res://assets/theme/emoji/1f60d.svg"),
	"star_struck": preload("res://assets/theme/emoji/1f929.svg"),
	"blowing_kiss": preload("res://assets/theme/emoji/1f618.svg"),
	"thinking": preload("res://assets/theme/emoji/1f914.svg"),
	"rolling_eyes": preload("res://assets/theme/emoji/1f644.svg"),
	"crying": preload("res://assets/theme/emoji/1f62d.svg"),
	"pleading": preload("res://assets/theme/emoji/1f97a.svg"),
	# People & Body
	"wave": preload("res://assets/theme/emoji/1f44b.svg"),
	"raised_back_of_hand": preload("res://assets/theme/emoji/1f91a.svg"),
	"thumbs_up": preload("res://assets/theme/emoji/1f44d.svg"),
	"thumbs_down": preload("res://assets/theme/emoji/1f44e.svg"),
	"clap": preload("res://assets/theme/emoji/1f44f.svg"),
	"pray": preload("res://assets/theme/emoji/1f64f.svg"),
	"muscle": preload("res://assets/theme/emoji/1f4aa.svg"),
	"handshake": preload("res://assets/theme/emoji/1f91d.svg"),
	"victory": preload("res://assets/theme/emoji/270c.svg"),
	"ok_hand": preload("res://assets/theme/emoji/1f44c.svg"),
	"fist_bump": preload("res://assets/theme/emoji/1f44a.svg"),
	"left_fist": preload("res://assets/theme/emoji/1f91b.svg"),
	"right_fist": preload("res://assets/theme/emoji/1f91c.svg"),
	"crossed_fingers": preload("res://assets/theme/emoji/1f91e.svg"),
	"rock_on": preload("res://assets/theme/emoji/1f918.svg"),
	"call_me": preload("res://assets/theme/emoji/1f919.svg"),
	"point_left": preload("res://assets/theme/emoji/1f448.svg"),
	"point_right": preload("res://assets/theme/emoji/1f449.svg"),
	"point_up": preload("res://assets/theme/emoji/1f446.svg"),
	"point_down": preload("res://assets/theme/emoji/1f447.svg"),
	# Animals & Nature
	"dog_face": preload("res://assets/theme/emoji/1f436.svg"),
	"cat_face": preload("res://assets/theme/emoji/1f431.svg"),
	"mouse_face": preload("res://assets/theme/emoji/1f42d.svg"),
	"hamster": preload("res://assets/theme/emoji/1f439.svg"),
	"rabbit": preload("res://assets/theme/emoji/1f430.svg"),
	"fox": preload("res://assets/theme/emoji/1f98a.svg"),
	"bear": preload("res://assets/theme/emoji/1f43b.svg"),
	"panda": preload("res://assets/theme/emoji/1f43c.svg"),
	"koala": preload("res://assets/theme/emoji/1f428.svg"),
	"tiger": preload("res://assets/theme/emoji/1f42f.svg"),
	"lion": preload("res://assets/theme/emoji/1f981.svg"),
	"cow": preload("res://assets/theme/emoji/1f42e.svg"),
	"pig": preload("res://assets/theme/emoji/1f437.svg"),
	"frog": preload("res://assets/theme/emoji/1f438.svg"),
	"monkey_face": preload("res://assets/theme/emoji/1f435.svg"),
	"sunflower": preload("res://assets/theme/emoji/1f33b.svg"),
	"rose": preload("res://assets/theme/emoji/1f339.svg"),
	"hibiscus": preload("res://assets/theme/emoji/1f33a.svg"),
	"four_leaf_clover": preload("res://assets/theme/emoji/1f340.svg"),
	"evergreen_tree": preload("res://assets/theme/emoji/1f332.svg"),
	# Food & Drink
	"red_apple": preload("res://assets/theme/emoji/1f34e.svg"),
	"orange": preload("res://assets/theme/emoji/1f34a.svg"),
	"lemon": preload("res://assets/theme/emoji/1f34b.svg"),
	"banana": preload("res://assets/theme/emoji/1f34c.svg"),
	"watermelon": preload("res://assets/theme/emoji/1f349.svg"),
	"grapes": preload("res://assets/theme/emoji/1f347.svg"),
	"strawberry": preload("res://assets/theme/emoji/1f353.svg"),
	"peach": preload("res://assets/theme/emoji/1f351.svg"),
	"cherries": preload("res://assets/theme/emoji/1f352.svg"),
	"pineapple": preload("res://assets/theme/emoji/1f34d.svg"),
	"tomato": preload("res://assets/theme/emoji/1f345.svg"),
	"avocado": preload("res://assets/theme/emoji/1f951.svg"),
	"hamburger": preload("res://assets/theme/emoji/1f354.svg"),
	"pizza": preload("res://assets/theme/emoji/1f355.svg"),
	"taco": preload("res://assets/theme/emoji/1f32e.svg"),
	"burrito": preload("res://assets/theme/emoji/1f32f.svg"),
	"popcorn": preload("res://assets/theme/emoji/1f37f.svg"),
	"shortcake": preload("res://assets/theme/emoji/1f370.svg"),
	"doughnut": preload("res://assets/theme/emoji/1f369.svg"),
	"hot_beverage": preload("res://assets/theme/emoji/2615.svg"),
	# Activities
	"soccer": preload("res://assets/theme/emoji/26bd.svg"),
	"basketball": preload("res://assets/theme/emoji/1f3c0.svg"),
	"football": preload("res://assets/theme/emoji/1f3c8.svg"),
	"baseball": preload("res://assets/theme/emoji/26be.svg"),
	"tennis": preload("res://assets/theme/emoji/1f3be.svg"),
	"volleyball": preload("res://assets/theme/emoji/1f3d0.svg"),
	"pool_8_ball": preload("res://assets/theme/emoji/1f3b1.svg"),
	"bowling": preload("res://assets/theme/emoji/1f3b3.svg"),
	"direct_hit": preload("res://assets/theme/emoji/1f3af.svg"),
	"trophy": preload("res://assets/theme/emoji/1f3c6.svg"),
	"sports_medal": preload("res://assets/theme/emoji/1f3c5.svg"),
	"game_die": preload("res://assets/theme/emoji/1f3b2.svg"),
	"video_game": preload("res://assets/theme/emoji/1f3ae.svg"),
	"artist_palette": preload("res://assets/theme/emoji/1f3a8.svg"),
	"performing_arts": preload("res://assets/theme/emoji/1f3ad.svg"),
	"musical_note": preload("res://assets/theme/emoji/1f3b5.svg"),
	"musical_notes": preload("res://assets/theme/emoji/1f3b6.svg"),
	"microphone": preload("res://assets/theme/emoji/1f3a4.svg"),
	"headphone": preload("res://assets/theme/emoji/1f3a7.svg"),
	"clapper_board": preload("res://assets/theme/emoji/1f3ac.svg"),
	# Travel & Places
	"car": preload("res://assets/theme/emoji/1f697.svg"),
	"taxi": preload("res://assets/theme/emoji/1f695.svg"),
	"bus": preload("res://assets/theme/emoji/1f68c.svg"),
	"police_car": preload("res://assets/theme/emoji/1f693.svg"),
	"ambulance": preload("res://assets/theme/emoji/1f691.svg"),
	"fire_engine": preload("res://assets/theme/emoji/1f692.svg"),
	"airplane": preload("res://assets/theme/emoji/2708.svg"),
	"rocket": preload("res://assets/theme/emoji/1f680.svg"),
	"flying_saucer": preload("res://assets/theme/emoji/1f6f8.svg"),
	"ship": preload("res://assets/theme/emoji/1f6a2.svg"),
	"house": preload("res://assets/theme/emoji/1f3e0.svg"),
	"building_construction": preload("res://assets/theme/emoji/1f3d7.svg"),
	"mountain": preload("res://assets/theme/emoji/26f0.svg"),
	"beach": preload("res://assets/theme/emoji/1f3d6.svg"),
	"earth_americas": preload("res://assets/theme/emoji/1f30e.svg"),
	"earth_asia": preload("res://assets/theme/emoji/1f30f.svg"),
	"star": preload("res://assets/theme/emoji/2b50.svg"),
	"crescent_moon": preload("res://assets/theme/emoji/1f319.svg"),
	"sun": preload("res://assets/theme/emoji/2600.svg"),
	"rainbow": preload("res://assets/theme/emoji/1f308.svg"),
	# Objects
	"watch": preload("res://assets/theme/emoji/231a.svg"),
	"mobile_phone": preload("res://assets/theme/emoji/1f4f1.svg"),
	"laptop": preload("res://assets/theme/emoji/1f4bb.svg"),
	"keyboard": preload("res://assets/theme/emoji/2328.svg"),
	"light_bulb": preload("res://assets/theme/emoji/1f4a1.svg"),
	"books": preload("res://assets/theme/emoji/1f4da.svg"),
	"open_book": preload("res://assets/theme/emoji/1f4d6.svg"),
	"pencil": preload("res://assets/theme/emoji/270f.svg"),
	"memo": preload("res://assets/theme/emoji/1f4dd.svg"),
	"paperclip": preload("res://assets/theme/emoji/1f4ce.svg"),
	"pushpin": preload("res://assets/theme/emoji/1f4cc.svg"),
	"scissors": preload("res://assets/theme/emoji/2702.svg"),
	"wrench": preload("res://assets/theme/emoji/1f527.svg"),
	"hammer": preload("res://assets/theme/emoji/1f528.svg"),
	"magnifying_glass": preload("res://assets/theme/emoji/1f50d.svg"),
	"locked": preload("res://assets/theme/emoji/1f512.svg"),
	"key": preload("res://assets/theme/emoji/1f511.svg"),
	"gift": preload("res://assets/theme/emoji/1f381.svg"),
	"party_popper": preload("res://assets/theme/emoji/1f389.svg"),
	"bell": preload("res://assets/theme/emoji/1f514.svg"),
	# Symbols
	"heart": preload("res://assets/theme/emoji/2764.svg"),
	"orange_heart": preload("res://assets/theme/emoji/1f9e1.svg"),
	"yellow_heart": preload("res://assets/theme/emoji/1f49b.svg"),
	"green_heart": preload("res://assets/theme/emoji/1f49a.svg"),
	"blue_heart": preload("res://assets/theme/emoji/1f499.svg"),
	"purple_heart": preload("res://assets/theme/emoji/1f49c.svg"),
	"black_heart": preload("res://assets/theme/emoji/1f5a4.svg"),
	"broken_heart": preload("res://assets/theme/emoji/1f494.svg"),
	"two_hearts": preload("res://assets/theme/emoji/1f495.svg"),
	"100": preload("res://assets/theme/emoji/1f4af.svg"),
	"check_mark": preload("res://assets/theme/emoji/2705.svg"),
	"cross_mark": preload("res://assets/theme/emoji/274c.svg"),
	"exclamation": preload("res://assets/theme/emoji/2757.svg"),
	"question": preload("res://assets/theme/emoji/2753.svg"),
	"eyes": preload("res://assets/theme/emoji/1f440.svg"),
	"collision": preload("res://assets/theme/emoji/1f4a5.svg"),
	"anger": preload("res://assets/theme/emoji/1f4a2.svg"),
	"dizzy": preload("res://assets/theme/emoji/1f4ab.svg"),
	"zzz": preload("res://assets/theme/emoji/1f4a4.svg"),
	"fire": preload("res://assets/theme/emoji/1f525.svg"),
	# Flags
	"flag_us": preload("res://assets/theme/emoji/1f1fa-1f1f8.svg"),
	"flag_gb": preload("res://assets/theme/emoji/1f1ec-1f1e7.svg"),
	"flag_ca": preload("res://assets/theme/emoji/1f1e8-1f1e6.svg"),
	"flag_au": preload("res://assets/theme/emoji/1f1e6-1f1fa.svg"),
	"flag_de": preload("res://assets/theme/emoji/1f1e9-1f1ea.svg"),
	"flag_fr": preload("res://assets/theme/emoji/1f1eb-1f1f7.svg"),
	"flag_es": preload("res://assets/theme/emoji/1f1ea-1f1f8.svg"),
	"flag_it": preload("res://assets/theme/emoji/1f1ee-1f1f9.svg"),
	"flag_jp": preload("res://assets/theme/emoji/1f1ef-1f1f5.svg"),
	"flag_kr": preload("res://assets/theme/emoji/1f1f0-1f1f7.svg"),
	"flag_cn": preload("res://assets/theme/emoji/1f1e8-1f1f3.svg"),
	"flag_in": preload("res://assets/theme/emoji/1f1ee-1f1f3.svg"),
	"flag_br": preload("res://assets/theme/emoji/1f1e7-1f1f7.svg"),
	"flag_mx": preload("res://assets/theme/emoji/1f1f2-1f1fd.svg"),
	"flag_ru": preload("res://assets/theme/emoji/1f1f7-1f1fa.svg"),
	"flag_nl": preload("res://assets/theme/emoji/1f1f3-1f1f1.svg"),
	"flag_se": preload("res://assets/theme/emoji/1f1f8-1f1ea.svg"),
	"flag_no": preload("res://assets/theme/emoji/1f1f3-1f1f4.svg"),
	"flag_fi": preload("res://assets/theme/emoji/1f1eb-1f1ee.svg"),
	"flag_dk": preload("res://assets/theme/emoji/1f1e9-1f1f0.svg"),
	"flag_ie": preload("res://assets/theme/emoji/1f1ee-1f1ea.svg"),
	"flag_pt": preload("res://assets/theme/emoji/1f1f5-1f1f9.svg"),
	"flag_ch": preload("res://assets/theme/emoji/1f1e8-1f1ed.svg"),
	"flag_be": preload("res://assets/theme/emoji/1f1e7-1f1ea.svg"),
	"flag_at": preload("res://assets/theme/emoji/1f1e6-1f1f9.svg"),
	"flag_pl": preload("res://assets/theme/emoji/1f1f5-1f1f1.svg"),
	"flag_tr": preload("res://assets/theme/emoji/1f1f9-1f1f7.svg"),
	"flag_ua": preload("res://assets/theme/emoji/1f1fa-1f1e6.svg"),
	"flag_nz": preload("res://assets/theme/emoji/1f1f3-1f1ff.svg"),
	"flag_ar": preload("res://assets/theme/emoji/1f1e6-1f1f7.svg"),
}

# Skin tone modifier codepoints (index matches Config value: 0=none, 1-5=tones)
const SKIN_TONE_MODIFIERS := ["", "1f3fb", "1f3fc", "1f3fd", "1f3fe", "1f3ff"]

# Emoji names that support skin tone modifiers
const SKIN_TONE_EMOJI: Array[String] = [
	"wave", "raised_back_of_hand", "thumbs_up", "thumbs_down",
	"clap", "pray", "muscle", "victory", "ok_hand", "fist_bump",
	"left_fist", "right_fist", "crossed_fingers", "rock_on",
	"call_me", "point_left", "point_right", "point_up", "point_down",
]

static var _name_lookup: Dictionary = {}
static var _skin_tone_textures: Dictionary = {} # "codepoint" -> Texture2D

static func _build_name_lookup() -> void:
	if not _name_lookup.is_empty():
		return
	for cat_entries in CATALOG.values():
		for entry in cat_entries:
			_name_lookup[entry["name"]] = entry

static func get_all_for_category(category: Category) -> Array:
	return CATALOG.get(category, [])

static func get_by_name(emoji_name: String) -> Dictionary:
	_build_name_lookup()
	return _name_lookup.get(emoji_name, {})

## Returns true if the emoji supports skin tone variants.
static func supports_skin_tone(emoji_name: String) -> bool:
	return emoji_name in SKIN_TONE_EMOJI

## Returns the codepoint for the emoji with the given skin tone applied.
## If tone is 0 (default) or emoji doesn't support tones, returns the base codepoint.
static func get_codepoint_with_tone(emoji_name: String, tone: int) -> String:
	var entry := get_by_name(emoji_name)
	if entry.is_empty():
		return ""
	var base_cp: String = entry["codepoint"]
	if tone <= 0 or tone > 5 or not supports_skin_tone(emoji_name):
		return base_cp
	return base_cp + "-" + SKIN_TONE_MODIFIERS[tone]

## Returns the texture for the emoji, optionally with skin tone applied.
## Skin tone textures are lazily loaded (not preloaded) to avoid loading 95
## textures at startup.
static func get_texture(emoji_name: String, tone: int = 0) -> Texture2D:
	if tone <= 0 or not supports_skin_tone(emoji_name):
		return TEXTURES.get(emoji_name)
	var cp := get_codepoint_with_tone(emoji_name, tone)
	if _skin_tone_textures.has(cp):
		return _skin_tone_textures[cp]
	var path := "res://assets/theme/emoji/" + cp + ".svg"
	if ResourceLoader.exists(path):
		var tex: Texture2D = load(path)
		_skin_tone_textures[cp] = tex
		return tex
	return TEXTURES.get(emoji_name) # Fallback to default

## Converts a hex codepoint (possibly multi-part like "1f1fa-1f1f8") to a
## Unicode character string.
static func codepoint_to_char(hex_codepoint: String) -> String:
	var result := ""
	for part in hex_codepoint.split("-"):
		result += char(part.hex_to_int())
	return result
